SELECT * FROM MEMBER;

DROP TABLE TB_FILE;

CREATE TABLE TB_FILE(
	IDX NUMBER,
	PARENT_SEQ NUMBER NOT NULL,
	ORIGINAL_FILE_NAME VARCHAR2(260 BYTE) NOT NULL,
	STORED_FILE_NAME VARCHAR2(36) NOT NULL,
	FILE_SIZE NUMBER,
	CRE_DATE DATE NOT NULL,
	PRIMARY KEY (IDX)
);

CREATE SEQUENCE TB_FILE_IDX_SEQ
START WITH 1
INCREMENT BY 1;

drop sequence tb_file_idx_seq;


INSERT INTO TB_FILE
VALUE(
	IDX, PARENT_SEQ, ORIGINAL_FILE_NAME, 
	STORED_FILE_NAME, FILE_SIZE, CRE_DATE)
VALUES(
	TB_FILE_IDX_SEQ.nextval, 1, '파일.TXT', 
	'UNIQUE_VALUE', 1024, SYSDATE);

commit;

SELECT * FROM TB_FILE;

delete from tb_file;
delete from member;

